<a href="https://colab.research.google.com/github/mongdaeng/est-wassup1/blob/main/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
# 메소드와 속성
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [ ]:
a = np.array(0)
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [ ]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [ ]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a)

#아래 결과 값은 보기 좋게 반환해준것

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [ ]:

a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [ ]:
a.shape
#2행 3열인데, 깊이가 2개

a.shape?

In [ ]:
#shape
a = np.array(3)
a, a.shape # 행렬아님

(array(3), ())

In [ ]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [ ]:

a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

# **3. size**

In [ ]:
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [ ]:

a = np.array([[1,2,3], [4,5,6]])
a.size

6

# **넘파이 배열**

In [ ]:

# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [ ]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5


In [ ]:
myArr

array([10, 56, 77, 23, 44])

In [ ]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [ ]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9


In [ ]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [ ]:
# 길이가 달라 에러 리턴 -> 행렬이 아니라서
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

[list([1, 2, 3, 4]) list([10, 20, 30, 40, 50]) list([100, 200])] <class 'numpy.ndarray'> 3
차원= 1, 구조 = (3,) 구조타입 = <class 'tuple'>, size = 3


<ipython-input-21-158910974d83>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  myArr21 = np.array(myList21)


# **넘파이 & 리스트 구분**

In [ ]:
# 리스트의 산술연산자 +, *
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: ignored

In [ ]:

print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가 (안의 값들을 곱하는 건 불가 )

[10, 30, 50, 10, 30, 50]


TypeError: ignored

In [ ]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [ ]:

arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


# **d type**

In [ ]:

# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [ ]:
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [ ]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64



# Inf와 **NaN**

In [ ]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

<ipython-input-29-6ab12ec6e7a4>:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
<ipython-input-29-6ab12ec6e7a4>:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [ ]:
np.log(0)

<ipython-input-33-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [ ]:
np.exp(-np.inf)

0.0

# **기술 통계 **

In [ ]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [ ]:

np.mean(x)  # 평균

4.8076923076923075

In [ ]:
np.var(x)  # 분산

115.23224852071006

In [ ]:
np.std(x)  # 표준 편차

10.734628476137871

In [ ]:
np.max(x)  # 최댓값

23

In [ ]:
np.min(x)  # 최소값

-24

In [ ]:
np.median(x)  # 중앙값

5.0

# **사분위수**

In [ ]:
np.percentile(x, 0)  # 최소값

-24.0

In [ ]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [ ]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [ ]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [ ]:
np.percentile(x, 100)  # 최댓값

23.0


# 넘파이 함수로 배열 **만들기**

In [ ]:

# 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [ ]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [ ]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int64


In [ ]:
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [ ]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [ ]:
# 메모리가 비어있음
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [ ]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [ ]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [ ]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])


# **reshape 구조의 재배열**

reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [ ]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [ ]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [ ]:

arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [ ]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [ ]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
print(np.arange(2,101,2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [ ]:

# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [ ]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(-1, 4)
# rehsape -1은, 행무관하고 n개의 컬럼을 만든다

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
# 사이즈가 맞아야 한다.
# np.arange(1, 21).reshape(-1, 7)

In [ ]:

a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [ ]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [ ]:

a.shape = 3, -1
a, a.shape

In [ ]:

a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [ ]:
a.shape = -1, 2
a, a.shape

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 (6, 2))

In [ ]:

a.shape = -1, 3
a, a.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [ ]:
# flatten
a.shape = -1
a, a.shape


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

# **넘파이배열의 자료형 형변환**

배열명2 = 배열명1.astype(자료형)
자료형 = np.float64, np.int32

In [ ]:

matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [ ]:

# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int64'))

In [ ]:

# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [ ]:

# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

ValueError: ignored

In [ ]:

# 정수형 => 문자열
matrix.astype('<U5')


array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [ ]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [ ]:

# 불린 -> 정수
matrix2.astype(int)


array([1, 0, 1, 1])

In [ ]:

# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [ ]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [ ]:

print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: ignored

In [ ]:

matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])


# **넘파이 배열의 인덱싱**

넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

In [ ]:

a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [ ]:
a[0]

1

In [ ]:

a[2]

5

In [ ]:

a[4]

9

In [ ]:

a[-1]

9

In [ ]:

a[-3]

In [ ]:
a[-5]

1

In [ ]:
a[[0, 2, 4]]

array([1, 5, 9])

In [ ]:
a

array([1, 3, 5, 7, 9])

In [ ]:

# 행렬 구조로 인덱싱도 가능하다
i = np.array([[1,3], [4,2]])
i

array([[1, 3],
       [4, 2]])

In [ ]:

# 넘파이배열1을 넘파이배열2로 인덱싱하는 경우. 넘파이배열2는 인덱스 번호로 인식
a[i]

array([[3, 7],
       [9, 5]])

In [ ]:

a[2] = 0
a

array([1, 3, 0, 7, 9])

In [ ]:

a[1] += 2
a

array([1, 5, 0, 7, 9])

In [ ]:

a[0] *= 6
a

array([6, 5, 0, 7, 9])


# 2D array


In [ ]:

a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [ ]:

a[0]

array([0, 1, 2, 3, 4])

In [ ]:

a[1]

array([5, 6, 7, 8, 9])

In [ ]:

a[2]

array([10, 11, 12, 13, 14])

In [ ]:
a[-1]

array([10, 11, 12, 13, 14])

In [ ]:
a[-2]

array([5, 6, 7, 8, 9])

In [ ]:

a[-3]

array([0, 1, 2, 3, 4])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a[0, 0]

0

In [ ]:

a[0, 1]

In [ ]:

a[0, 2]

In [ ]:

a[1, 0]

5

In [ ]:

a[1, 1]

6

In [ ]:

a[1, 2]

7

In [ ]:
a[2, 0]

10

In [ ]:
a[2, 1]

11

In [ ]:
a[2, 2]

12

In [ ]:

a[-1, 0]

10

In [ ]:

a[-1, 1]

11

In [ ]:

a[-1, 2]

12

In [ ]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:

a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [ ]:

a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [ ]:

a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [ ]:

matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [ ]:

# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [ ]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0]


0

In [ ]:
matrix_b[0][0]

0

In [ ]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 2차원 마지막행 마지막열 -> 3행 4열
matrix_b[-1,-1]

11

In [ ]:
matrix_b[-1][-1]

11

In [ ]:
matrix_b[2][3]

11

In [ ]:

# matrix_b에서 3번째행 1번째열의값을 100으로 변경해보자
matrix_b[2,0] = 100
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])


# **넘파이배열 슬라이싱**

1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]
2차원
넘파이배열[행, 열] = [start:end:step, start2:end2:step2]

# **1D array**

In [ ]:

a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [ ]:
a[:]

array([1, 3, 5, 7, 9])

In [ ]:

 a[1:]

array([3, 5, 7, 9])

In [ ]:
a[-1:]

array([9])

In [ ]:
a[:3]

array([1, 3, 5])

In [ ]:
a[:-1]

array([1, 3, 5, 7])

In [ ]:
a[1:4]

array([3, 5, 7])

In [ ]:
a[1:-1]

array([3, 5, 7])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[::2]

array([0, 2, 4, 6, 8])

In [ ]:

a[::5]

array([0, 5])

In [ ]:

a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:

# 홀수
a[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
a[3::2]

array([3, 5, 7, 9])

In [ ]:

a[:-2:2]

array([0, 2, 4, 6])

In [ ]:
a[:-6:2]

array([0, 2])

In [ ]:
a[2:-2:2]

array([2, 4, 6])


# 2D array

In [ ]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

In [ ]:

a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:

a[-1:]

array([9])

In [ ]:

a[-3:]

array([7, 8, 9])

In [ ]:

a[:0]

array([], dtype=int64)

In [ ]:
a[:2]


array([0, 1])

In [ ]:

a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:

a[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:

a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[:,:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[:, 1:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49],
       [51, 52, 53, 54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66, 67, 68, 69],
       [71, 72, 73, 74, 75, 76, 77, 78, 79],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:

a[:, 3:]

array([[13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49],
       [53, 54, 55, 56, 57, 58, 59],
       [63, 64, 65, 66, 67, 68, 69],
       [73, 74, 75, 76, 77, 78, 79],
       [83, 84, 85, 86, 87, 88, 89],
       [93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[:, -1:]

array([[19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

In [ ]:
a[:, -4:]

array([[16, 17, 18, 19],
       [26, 27, 28, 29],
       [36, 37, 38, 39],
       [46, 47, 48, 49],
       [56, 57, 58, 59],
       [66, 67, 68, 69],
       [76, 77, 78, 79],
       [86, 87, 88, 89],
       [96, 97, 98, 99]])

In [ ]:
a[:, :1]

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [ ]:
a[:, :5]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54],
       [60, 61, 62, 63, 64],
       [70, 71, 72, 73, 74],
       [80, 81, 82, 83, 84],
       [90, 91, 92, 93, 94]])

In [ ]:
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[:, :-1]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35, 36, 37, 38],
       [40, 41, 42, 43, 44, 45, 46, 47, 48],
       [50, 51, 52, 53, 54, 55, 56, 57, 58],
       [60, 61, 62, 63, 64, 65, 66, 67, 68],
       [70, 71, 72, 73, 74, 75, 76, 77, 78],
       [80, 81, 82, 83, 84, 85, 86, 87, 88],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [ ]:
a[:, :-2]

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [20, 21, 22, 23, 24, 25, 26, 27],
       [30, 31, 32, 33, 34, 35, 36, 37],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55, 56, 57],
       [60, 61, 62, 63, 64, 65, 66, 67],
       [70, 71, 72, 73, 74, 75, 76, 77],
       [80, 81, 82, 83, 84, 85, 86, 87],
       [90, 91, 92, 93, 94, 95, 96, 97]])

In [ ]:
a[:, 0:1]

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [ ]:
a[:, 2:3]

array([[12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [ ]:
a[:, 1:-1]

array([[11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28],
       [31, 32, 33, 34, 35, 36, 37, 38],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [51, 52, 53, 54, 55, 56, 57, 58],
       [61, 62, 63, 64, 65, 66, 67, 68],
       [71, 72, 73, 74, 75, 76, 77, 78],
       [81, 82, 83, 84, 85, 86, 87, 88],
       [91, 92, 93, 94, 95, 96, 97, 98]])

In [ ]:
a = np.arange(10, 100).reshape(9, 10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:

a[2:5, :]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:

a[:, 2:5]


array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [ ]:

a[2:5, 2:5]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [ ]:
a[::2, ::2]

array([[10, 12, 14, 16, 18],
       [30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [ ]:

a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:

a[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [ ]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 numpy.ndarray,
 2)

In [ ]:

# 1차원 슬라이싱, 1행만 출력
matrix_c[0, :], matrix_c[0]

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [ ]:

# 2차원 슬라이싱, 1번째행 2번째행 출력
matrix_c[0:2, :], matrix_c[0:2]

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]))

In [ ]:

# 1번째열만 출력
matrix_c[:, 0]

array([ 1,  6, 11, 16, 21])

In [ ]:

# 3,4 번째열만 출력
matrix_c[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [ ]:
# 특정행의 특정열 슬라이싱
matrix_c[0:3, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [ ]:
# 홀수번째 행만 출력
matrix_c[::2, ::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [ ]:

# 짝수번쨰행 + 홀수번째열
matrix_c[1::2, ::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

In [ ]:

# 리버스 인덱싱
print(matrix_c[::-1, ::]) # 행 뒤집기
print(matrix_c[::, ::-1]) # 열 뒤집기

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


# **전치행렬**

넘파이배열.T : 행과 열 구조 변경 image-2.png

In [ ]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [ ]:

# reshape과 transpose은 값이 다름을 유의
print(matrix_d.reshape(2,3))

[[1 2 3]
 [4 5 6]]



# **난수로 구성된 넘파이 배열**

np.random.randint(start, end, n) : 정수 난수
np.random.randint(start, end, (i, j))

In [ ]:

np.random?

In [ ]:

# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([2, 8, 1, 5, 2, 7, 5, 6, 5, 1])

In [ ]:

# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[3, 5, 6, 4, 7],
       [5, 6, 2, 4, 1]])


# **섞기**

np.random.shuffle(넘파이배열) 원본에 바로 적용

In [ ]:
np.random.shuffle?

In [ ]:

# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:

np.random.shuffle(matrix_e)
matrix_e

array([10,  1,  6,  9,  3,  4,  7,  8,  5,  2])


#Quiz : 1~46까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [ ]:
num= np.arange(1,47)
np.random.shuffle(num)
num[:6]


array([39, 44, 27, 28, 45, 37])

In [ ]:

np.random.randint(1,47,6)

array([39, 34,  2, 31, 32,  7])


# **실수 난수**

np.random.randn(n) np.random.randn(i, j)

In [ ]:

np.random.randn?

In [ ]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([-1.53682043,  2.40953294,  0.1609781 , -1.19773809, -0.51737918,
        0.4625291 ,  0.82252265,  0.52852148,  1.49895964, -0.02502712])

In [ ]:

matrix2 = np.random.randn(4, 4)
matrix2

array([[-3.12019476,  0.85037939,  0.477647  , -0.45605229],
       [ 2.08551914,  0.67510386, -0.93892409, -0.31310597],
       [-0.95549727,  0.91568566,  0.13932763, -0.88731444],
       [-0.02573893, -1.09379833,  0.19937237,  0.23037609]])

In [ ]:
matrix1.max(), matrix1.min()

(2.409532940173, -1.53682043368813)


# **집계함수에서의 축**

2차원에서의 집계합수(sum, mean)
axis = 0, 1
np.sum(넘파이배열, axis=0/1)
np.mean(넘파이배열, axis=0/1)
np.sort(넘파이배열, axis=0/1)

In [ ]:

m1 = np.random.randint(1, 50, (5,5))
m1

array([[31, 45, 45, 11, 17],
       [ 8, 33, 25,  1,  8],
       [23, 36, 32, 34, 26],
       [21, 27,  5, 27,  3],
       [34,  9,  3,  1, 26]])

In [ ]:

np.sum(m1, axis=0) # (x)행 합계

array([117, 150, 110,  74,  80])

In [ ]:

np.sum(m1, axis=1) # 열(y) 합계

array([149,  75, 151,  83,  73])

In [ ]:

# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

149


# np.sort()

In [ ]:

# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[ 9,  6, 43],
       [33, 16, 38],
       [40, 42,  2],
       [48,  1, 25]])

In [ ]:
np.sort?

In [ ]:

np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[ 9,  1,  2],
       [33,  6, 25],
       [40, 16, 38],
       [48, 42, 43]])

In [ ]:

m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[48,  1, 25],
       [40, 42,  2],
       [33, 16, 38],
       [ 9,  6, 43]])

In [ ]:

np.sort(m2, axis=1) # 열방향 오름차순

array([[ 6,  9, 43],
       [16, 33, 38],
       [ 2, 40, 42],
       [ 1, 25, 48]])

In [ ]:

np.sort(m2, axis=1) # 열방향 오름차순

array([[ 6,  9, 43],
       [16, 33, 38],
       [ 2, 40, 42],
       [ 1, 25, 48]])


# **인덱스 소팅**

np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [ ]:

x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값

array([2, 1, 0])

In [ ]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])


# **넘파이 배열 요소 추가와 삭제(12/18)**

삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
삭제

np.delete(배열명, 위치인덱스, axis=0/1)

In [ ]:

m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:

np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:

m3[-1]

10

In [ ]:

np.insert?

In [ ]:

np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [ ]:
np.insert(m3, len(m3), 500)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [ ]:

m4 = np.arange(1,10).reshape(3,3)
m4


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:

np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [ ]:

# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [ ]:

m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [ ]:

# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [ ]:

# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [ ]:

m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:

np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

# **배열 합치기**

np.vstack((배열1,배열2....)) : 세로 합치기
np.hstack((배열1,배열2....)) : 가로 합치기
np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [ ]:

a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [ ]:

d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [ ]:

f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [ ]:

f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

# **boolean indexing, mask**

조건절의 결과는 True, False로 반환
True인 결과의 데이터 반환
넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [ ]:
matrix = np.arange(1, 21)
matrix


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:

matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:

(matrix > 10).sum()

10


# Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [ ]:
num = np.random.randint(1,100,30)
(num > 30) & (num < 70)

array([False,  True, False, False,  True, False,  True,  True,  True,
        True, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False,  True,
       False, False,  True])

In [ ]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)] #boolean 인덱싱

(array([73, 44, 19, 13, 20, 18, 22, 52, 13, 30, 34, 39, 56, 15, 97, 86, 88,
        38, 77,  5, 52, 60, 76, 34, 72,  6, 74, 55,  1, 85]),
 array([44, 52, 34, 39, 56, 38, 52, 60, 34, 55]))

In [ ]:

# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([19, 13, 20, 18, 22, 13, 30, 15,  5,  6,  1])

In [ ]:

# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([97,  5,  6,  1])

In [ ]:

 num[~(num < 10) | (num > 90)]


array([73, 44, 19, 13, 20, 18, 22, 52, 13, 30, 34, 39, 56, 15, 97, 86, 88,
       38, 77, 52, 60, 76, 34, 72, 74, 55, 85])


# **fancy indexing(filtering)**

넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

넘파이배열1[넘파이배열2]
넘파이배열2 : 인덱스 역할 (only 정수형)

In [ ]:

n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([92, 10, 84, 16, 55, 35, 69, 46, 79, 58, 75, 40, 28, 47, 42, 45, 39,
        68, 95, 93, 51, 44, 53, 46, 53, 65, 25, 32, 61, 30]),
 array([92, 84, 16, 75, 51]))


# **np.where()를 이용한 필터링**

np.where(조건식) : 조건식 만족하는 인덱스 반환
np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [ ]:

np.where?

In [ ]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [ ]:
b = np.arange(20, 31) #20~31까지 만들고
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4]),))