<a href="https://colab.research.google.com/github/mongdaeng/est-wassup1/blob/main/02_Numpy_Quiz_%E1%84%89%E1%85%B5%E1%86%AF%E1%84%89%E1%85%B3%E1%86%B8%E1%84%8B%E1%85%AD%E1%86%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [2]:
import numpy as np

In [ ]:
data = ['강아지', '원숭이', '꽃', '45', '100']
arr = np.array(data)
arr

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')

In [ ]:
arr.ndim

1

In [ ]:
arr.size

5

In [ ]:
arr.dtype

dtype('<U3')

In [ ]:
arr.shape

(5,)

#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.ones((2,3),dtype=np.int64)
arr

array([[1, 1, 1],
       [1, 1, 1]])

#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [ ]:
arr = np.arange(51,81)
arr

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [ ]:
arr2 = arr.reshape(6,5)
arr2

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [ ]:
arr3 = arr2.astype(float)
arr3.dtype

dtype('float64')

#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [ ]:
arr2d = np.array([[ 1,  4,  5,  6],[56, 23, 45, 67],[ 8,  4,  6, 10]])
print(arr2d.flatten()[5:-1])

[23 45 67  8  4  6]


#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [3]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[0]=10
arr[7:]=0
arr

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다.

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [4]:
np.random.randint(10, 99, (5,5))

array([[95, 44, 33, 91, 11],
       [42, 49, 87, 82, 13],
       [42, 39, 63, 63, 68],
       [13, 23, 75, 77, 37],
       [15, 73, 31, 89, 76]])

#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [10]:
a = np.random.randint(1,100,7)
print(a)
np.max(a)

[10 17 42 80 16 95 87]


95

In [11]:
np.min(a)

10

#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]]
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [23]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr1 = np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19]])
arr2 = np.array([[21, 22, 23],[24, 25, 26],[27, 28, 29]])

#result1
result1 = np.hstack((arr,arr1,arr2))

result1


array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [24]:

#result2
result2 = np.vstack((arr,arr1,arr2))

result2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라.

```
arr = np.random.choice(100, 40, replace=False)

Before =>

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [29]:
a = np.random.choice(100,40, replace=False)
a, a[np.where(a>50)], a[a>50]

(array([77, 58, 90, 61, 71, 66, 49, 69,  0, 40, 67, 62, 74, 50, 85, 45, 51,
        24, 92,  1, 44, 38, 79, 63,  6, 81, 57,  9, 17, 11, 39, 25, 83, 18,
        43, 36, 59,  4, 55, 93]),
 array([77, 58, 90, 61, 71, 66, 69, 67, 62, 74, 85, 51, 92, 79, 63, 81, 57,
        83, 59, 55, 93]),
 array([77, 58, 90, 61, 71, 66, 69, 67, 62, 74, 85, 51, 92, 79, 63, 81, 57,
        83, 59, 55, 93]))

#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [30]:
kor = np.array( [60,55,70,30,20,90])

In [32]:
#1 최대값
np.max(kor)

90

In [35]:
#2 80점 이상
kor[kor>=80]

array([90])

In [38]:
#3 50점 이상 ~80점 이하
kor[(kor>=50) & (kor<=80)]

array([60, 55, 70])

In [42]:
#4 국어점수 평균
np.average(kor),

#소수점 정리
round(kor.mean(),3)

54.167

In [44]:
#5 국어 점수 합
np.sum(kor)

325

In [48]:
#6 40점 이하 삭제

kor1 = kor
num = kor[kor<=40]
kor1, num, np.delete(kor1, np.where(kor<=40))

(array([60, 55, 70, 30, 20, 90]), array([30, 20]), array([60, 55, 70, 90]))

In [50]:
#7 50점 이상인 데이터에 가산점 10%

np.where(kor>=50, kor*1.1, kor)

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [52]:
#8 국어점수 top3 ->잘 못풀었던 문제임

np.sort(kor)[::-1][:3]
kor[np.argsort(kor)[::-1][:3]]



array([90, 70, 60])

In [54]:
#9 국어 점수 70점 이상이면 합격, 아니면 불합격

kor, np.where(kor>=70, "합격", "불합격")

(array([60, 55, 70, 30, 20, 90]),
 array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3'))